name: Viewer

on:
  push:
    paths:
      - 'viewer/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: yarn
      working-directory: viewer
    - run: yarn build
      working-directory: viewer
